/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as JoinStoreIdRouteImport } from './routes/join.$storeId'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantNewRouteImport } from './routes/merchant/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinStoreIdRoute = JoinStoreIdRouteImport.update({
  id: '/join/$storeId',
  path: '/join/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantNewRoute = MerchantNewRouteImport.update({
  id: '/merchant/new',
  path: '/merchant/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/wallet': typeof WalletRoute
  '/join/$storeId': typeof JoinStoreIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/wallet': typeof WalletRoute
  '/join/$storeId': typeof JoinStoreIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant': typeof MerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/wallet': typeof WalletRoute
  '/join/$storeId': typeof JoinStoreIdRoute
  '/merchant/new': typeof MerchantNewRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/wallet'
    | '/join/$storeId'
    | '/merchant/new'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashier'
    | '/wallet'
    | '/join/$storeId'
    | '/merchant/new'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/cashier'
    | '/wallet'
    | '/join/$storeId'
    | '/merchant/new'
    | '/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashierRoute: typeof CashierRoute
  WalletRoute: typeof WalletRoute
  JoinStoreIdRoute: typeof JoinStoreIdRoute
  MerchantNewRoute: typeof MerchantNewRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$storeId': {
      id: '/join/$storeId'
      path: '/join/$storeId'
      fullPath: '/join/$storeId'
      preLoaderRoute: typeof JoinStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/new': {
      id: '/merchant/new'
      path: '/merchant/new'
      fullPath: '/merchant/new'
      preLoaderRoute: typeof MerchantNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashierRoute: CashierRoute,
  WalletRoute: WalletRoute,
  JoinStoreIdRoute: JoinStoreIdRoute,
  MerchantNewRoute: MerchantNewRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
